### ISSUE TITLE
Allow basic HTML in Subtitles

### ISSUE THREAD

**Issue by DannyOutlaw** [philiparthurmoore/Subtitles#39]
I would love to be able to add a simple text link in the subtite

**Comment by philiparthurmoore** [comment]
Hi @DannyOutlaw. You can do this by [modifying](https://github.com/philiparthurmoore/Subtitles/blob/7f2942f4048ee40576680fef56397b6fc7dc7145/admin/subtitles-admin.php#L242) the `$subtitles_allowed_tags` array. I need to add in a way for you to do that without messing with the plugin though. I'll leave this issue open until I update the plugin to let you change this array via filter.

**Comment by philiparthurmoore** [comment]
This will be fixed in the next release. See the [commit](https://github.com/philiparthurmoore/Subtitles/commit/71decdd6f62f6ca74894d6f084e3e09ad2943ddf) for an example of how this will be handled.
