### ISSUE TITLE
Subtitles repeats and conflicts with my email social share code

### ISSUE THREAD

**Issue by MissShugah** [philiparthurmoore/Subtitles#40]
Hi Philip,

I'm in love with subtitles but when I use it the social share code in my theme reacts and converts my email share button into text exposing all of the information that goes along with it. The twitter & facebook share buttons are not affected. I'm unsure how to fix this but I did look in my files and dont see "get-titles" or "get_the_titles" & my issue isnt Raw HTML anyway so title commands may not be the problem. Also, in addition to the proper space, the subtitle appears again this time directly above the exploded social share code  My developer insists the issue is your plugin so now I have to decide to remove the social share code and hope everything works fine or remove your plugin and lose the effortless subtitle functionality I need.

Here is a photo of what happens when your plugin is activated
https://pbs.twimg.com/media/CA4J8YyVEAAXBhc.png

here is how it should look - plugin not activated
http://www.drcarlhart.com/what-happens-after-nonviolent-drug-offender-are-released/

Please advise on what I should do, thank you very much.

Shug

**Comment by philiparthurmoore** [comment]
Hi @MissShugah. Is your social sharing coming from a plugin or is it directly in your theme? Can you show me that code?

**Comment by MissShugah** [comment]
The social sharing is a theme shortcode coded into the theme itself to
appear at the bottom of all of my posts. Not sure how to send code, Here's
a copy of whats in there, let me know if there is a better way to receive
it.


<?php get_header(); ?>

  <div class="x-container max width main">
    <div class="offset cf">
      <div class="<?php x_main_content_class(); ?>" role="main">
        <?php while ( have_posts() ) : the_post(); ?>
          <?php x_get_view( 'ethos', 'content', get_post_format() ); ?>
           <?php echo do_shortcode('[share facebook="true" twitter="true"
email="true"]'); ?>
          <?php x_get_view( 'global', '_comments-template' ); ?>
        <?php endwhile; ?>

      </div>

      <?php if ( $fullwidth != 'on' ) : ?>
        <?php get_sidebar(); ?>
      <?php endif; ?>

    </div>
  </div>

<?php get_footer(); ?>

**Comment by philiparthurmoore** [comment]
Okay, the reason this is happening is because your shortcode stuff is inside of your Loop (see [this](https://github.com/philiparthurmoore/Subtitles#subtitles-dont-show-up-on-my-site)). The only way to fix this "easily" would be to disable automatic subtitles and then using the built-in template tags that come with the plugin. Where is the code for your post titles? I don't see that in the above snippet.

**Comment by MissShugah** [comment]
I'm thinking of removing the short code completely & searching for a
lightweight share plugin with more functionality.  Hopefully the plugin
will function outside of the loop & that will eliminate the issue. I prefer
to keep subtitles automatic. I will let you know if it works after my Yoga
class. :)

Cheers!

**Comment by philiparthurmoore** [comment]
Sounds good. Let me know. Cheers.

**Comment by MissShugah** [comment]
Problem solved. Taking your tip about the "loop" I moved the short code further down in the same div and problem went away. :)

**Comment by philiparthurmoore** [comment]
Wonderful. Thanks for letting me know!
