### ISSUE TITLE
insert the sub-title in slider revolution

### ISSUE THREAD

**Issue by hamzan95** [philiparthurmoore/Subtitles#41]
Hello i have a roblem and i hope u can help me am using Subtitles Plugin and it works perfect but i need to put the subtitle uner the primary title in the slider show 
so in revolution slider i have an option called meta tags so if i want to show the title related to the Post i  use %title%  
i need to insert the subtitle under the primary title any one can help me
![prblm](https://cloud.githubusercontent.com/assets/11726590/6906248/e3549c36-d72d-11e4-8a05-e8707eb1f328.png)

**Comment by philiparthurmoore** [comment]
Hi @hamzan95. I'm afraid that I do not have a suitable answer for you. I think that this would require digging into the Slider Revolution code and adding support for Subtitles to that plugin, not the other way around. Subtitles comes with a [fairly extensive API](https://github.com/philiparthurmoore/Subtitles#adding-subtitles-support-into-custom-post-types) and this shouldn't be too hard to pull off, but it will require some custom work on your end. Cheers.

**Comment by hamzan95** [comment]
thank you so much for the replay  i hope i get a solution for this cause i need it and it's gonna be helpful for many people thanks again.Cheers
