### ISSUE TITLE
Adding a class to subtitles?

### ISSUE THREAD

**Issue by MissShugah** [philiparthurmoore/Subtitles#42]
Hello,

I use 2 different title styles on my site & I'd like to apply the appropriate subtitle style to each one via my global css. How can I name them separately or what is the best way to get this done?

**Comment by philiparthurmoore** [comment]
Do you mean that you would like to have a separate style for your subtitles and a separate title for your normal titles? Subtitles already comes with a CSS class `.entry-subtitle`. Are you not able to take control using just that class? Can you show me the HTML output currently? Thanks.

**Comment by MissShugah** [comment]
Let's say posts 1-40 use blue font at 50px with papyrus font

And posts 41-59 use black font at 75px with comic sans

Using .entry-subtitle only allows me to choose 1 style globally. How can I
style both separately & globally?

**Comment by philiparthurmoore** [comment]
Ah. Seems like something you should be able to do with CSS. Global would be `.entry-subtitle` and specific would look something like this:

```css
.post-3859 .entry-subtitle { }
```

Each post in WordPress already has a unique class on it so you should be able to select your subtitles in this manner.

**Comment by MissShugah** [comment]
Yes. Postid is the method I'm using but since I have a lot of posts I was
wondering if there was a way to style multiple posts at once rather than
use separate postid numbers for each post. If I continue to use postids, I
will end up with separate css for posts 41, 42, 43..... all the way up to
59. Meanwhile posts 1 to 40 can be effortlessly styled under class
"entry-subtitle."

Does that make sense?

Perhaps this is not possible.  Ideally I would like to use default
.entry-subtitle for half my posts & perhaps .Large.entry-subtitle for the
other half.

**Comment by philiparthurmoore** [comment]
I see what you mean. This isn't really possible right now; you could look into using `:not` with a combination of `:nth-child` (see an [example](http://stackoverflow.com/questions/12289853/css-notfirst-child-selector)) to dynamically style a set of posts that contain a subtitle. Or you could do this from within your own theme and give your first 40 posts a certain class. I think it would be very easy to do inside of your theme, much easier than doing it with Subtitles.

**Comment by MissShugah** [comment]
Thank you. I got my theme to add a class to posts as suggested. Thanks for
the tip.  :)
