### ISSUE TITLE
Subtitle is covering content on mobile

### ISSUE THREAD

**Issue by MissShugah** [philiparthurmoore/Subtitles#43]
Hello,

I am unsure who would be best to solve this problem (theme support or you) so I’m trying you first. 
The plugin works well in desktop view but on mobile my entry content pretends the subtitle isnt there so my 1st paragraph sits on top of it right underneath the h1.

A workaround I am using it this:

@media (max-width:480px) {
.single-post .entry-content {
margin-top: 70% !important;
margin-left: 5%;
margin-right: 5%;
}
}

But this method isnt great because each post is different causing me to spend a lot of time guessing what the correct margin should be & testing it out.

I’m not sure if this is a plugin problem since the plugin works on desktop, but I’m trying you first. Perhaps there is a css trick for this?

Please advise, thank you.

mobile view with css: http://imgur.com/NVOZvlc
mobile view without css: http://imgur.com/8EO8eeC

**Comment by philiparthurmoore** [comment]
This sounds like a theme CSS issue. Can you please give me a live URL and I'll take a look? Thanks.

**Comment by MissShugah** [comment]
This is a post I fixed
http://www.drcarlhart.com/black-intellectual-does-not-mean-race-expert/

This is a post I didn't fix yet
http://www.drcarlhart.com/patrick-kennedy-wants-keep-marijuana-illegal/

**Comment by philiparthurmoore** [comment]
I'm very sorry for my late response. I have been swamped. I will take a look at this tomorrow.

**Comment by philiparthurmoore** [comment]
Hi @MissShugah. I just looked at your CSS and it seems like you put `absolute` positioning on the entry subtitle. Any reason for this? Why can't you use `relative` positioning like how it should be displayed by default? Thanks.

**Comment by philiparthurmoore** [comment]
Closing this out since it's a theme issue and not a plugin issue. Feel free to update me if you run into plugin-related issues in the future. Thanks.
