### ISSUE TITLE
Compatibility with html title and wp_title()

### ISSUE THREAD

**Issue by lmartins** [philiparthurmoore/Subtitles#44]
Hi,

Thank your for this really useful plugin.
Currently using Subtitles and wp_title() to generate pages title attribute, there's an issue because what gets outputted is something like:
```
<title> » <span class="entry-title-primary">Nulla consequat massa quis enim</span> <span class="entry-subtitle">Subtítulo do artigo</span>Disclosure</title>
```
Is this something you planning to fix?

**Comment by philiparthurmoore** [comment]
Hi there. This shouldn't be happening at all. Where exactly are you seeing this?

**Comment by lmartins** [comment]
Im seeing it on my blog, but i've just noticed it only happens locally, not on the server:
http://intangible.life/modern-wordpress-workflow-theming/

I'll close this for now and report back if I see it happening on server. Thaks.

**Comment by philiparthurmoore** [comment]
Great, thanks. Subtitle stuff should only affect everything inside The Loop, and not your page title. If you see this come up again let me know.
