### ISSUE TITLE
RSS Feed-add subtitle 

### ISSUE THREAD

**Issue by jburess** [philiparthurmoore/Subtitles#45]
Hello! 

Sorry if this is a dup, I try to submit a question through another area on here but not sure if it was the right place.    

I love this plugin, is it possible to pass through the subtitle in the rss feed?  I'm using mailchimp to send daily email of new blog post and would like to include the subtitle. 

Thanks! 
Julie

**Comment by philiparthurmoore** [comment]
Hi Julie. Subtitles [aren't shown](https://github.com/philiparthurmoore/Subtitles/blob/master/public/class-subtitles.php#L568) in feeds. There's no way to override this that doesn't involve changing the plugin. I'll create a way to easily override this. Just to be clear, do you want your subtitle to be shown in Subject lines or what? Can you show me a screenshot of where you expect them to show up? Thanks.

**Comment by jburess** [comment]
Hi Philip,

Thank you for getting back to me.  This is how it currently shows, Screen Shot 2015-04-10 at 8.27.07 AM.png

is it possible to create under the main title, it could get long if we added to the end of the title.  Or possibly below the pic, right above the descriptions?

Thanks!
Julie﻿

**Comment by philiparthurmoore** [comment]
Hi Julie﻿. No screenshot was attached to [your message](https://github.com/philiparthurmoore/Subtitles/issues/45). Can you upload it directly on GitHub? Very sorry for my late response. I've been swamped. Thanks.

**Comment by jburess** [comment]
Hi Phillip,

Thats strange, I checked the email I sent and it shows it was attached.  I haven't uploaded to GitHub, but I will take a look, any special place?

I've tried to attach it again here just in case.

Thanks!
Julie
Screen Shot 2015-04-10 at 8.27.07 AM.png﻿

**Comment by philiparthurmoore** [comment]
Hi Julie. Yes, please upload them here: https://github.com/philiparthurmoore/Subtitles/issues/45. Email attachments do not appear to work with GitHub. Thank you.

**Comment by philiparthurmoore** [comment]
Hi Julie. Do you still need help with this?

**Comment by jburess** [comment]
Hi Phil,  thanks for checking in.  My client is on hold now for this but appreciate all the help! 

Take Care, Julie

**Comment by philiparthurmoore** [comment]
Thanks Julie. I'll close this out for now then. Please feel free to re-open and update when the client moves forward.

Cheers,
Philip
