### ISSUE TITLE
If hiding subtitles in comment area, why setting font-size?

### ISSUE THREAD

**Issue by Volker-E** [philiparthurmoore/Subtitles#46]
class-subtitles.php line 526f. Why adding `font-size` to hidden element? Should be removed IMHO.

**Comment by philiparthurmoore** [comment]
That's a good question. Looks like this is legacy stuff leftover from https://github.com/philiparthurmoore/Subtitles/commit/175762c87106209d11544d5a6cd8197584c8044d. I'd be fine removing it.

**Comment by Volker-E** [comment]
:+1:
