### ISSUE TITLE
Hide subtitle in admin area for certain pages/templates

### ISSUE THREAD

**Issue by tienvooracht** [philiparthurmoore/Subtitles#47]
Hi,

Awesome plugin! Got one question though: is it possible to hide the subtitle box for certain specific pages? Perhaps when using a certain template?

For instance i'd like to hide the subtitle box on the page that is set as homepage.

Thanks in advance!

**Comment by philiparthurmoore** [comment]
Hi there. There should be a way to do this by removing these actions:

```php
			if ( version_compare( $GLOBALS['wp_version'], '4.1-alpha', '<' ) ) {
				add_action( 'edit_form_after_title', array( &$this, 'build_subtitle_input' ) );
			} else {
				add_action( 'edit_form_before_permalink', array( &$this, 'build_subtitle_input' ) );
			}
```

The code is a bit involved, though. See [this thread](http://wordpress.stackexchange.com/questions/36013/remove-action-or-remove-filter-with-external-classes) for more information. I can look into this a bit later but wanted to follow up with you and point you in the right direction. I'll update this Issue if I come up with a useful snippet. Thanks.
