### ISSUE TITLE
subtitle repeats itself in main content

### ISSUE THREAD

**Issue by SabrinaHD** [philiparthurmoore/Subtitles#48]
Hello Thank you for making th subtitle plugin! is it updatet for newest wordpress version? I attatched an image to show my problem.

Thank you and best wishes,
Sabrina

![subtitle-sabrina-heuer de_slash_ein-plaedoyer-fuer-die-filmsynchronisation](https://cloud.githubusercontent.com/assets/12979058/8267776/11e2097e-176d-11e5-9dea-de3590260234.jpg)

**Comment by philiparthurmoore** [comment]
Hi there. Please see [this](https://github.com/philiparthurmoore/Subtitles#theres-weird-html-showing-up-on-my-site). Cheers.
