### ISSUE TITLE
Showing Subtitles on single posts conflicts with page title tag

### ISSUE THREAD

**Issue by themechills** [philiparthurmoore/Subtitles#50]
Hi Philip,

Firstly, great plugin so thanks for sharing it with the community.

My question relates to the fact that I only want the subtitles showing in single page views. I got this working with this:

```
function theme_slug_mod_supported_views() {
    if ( is_archive() || is_home() ) {
        return false;
    }

    if ( is_singular() ) {
        return true;
    }
} 
add_filter( 'subtitle_view_supported', theme_slug_mod_supported_views' );
```

Though after following the above approach it interferes with the title tag of the site. Any idea why this would be happening?

Thanks,

Leo

**Comment by philiparthurmoore** [comment]
Thanks Leo. Can you provide me with more information about this:

> Though after following the above approach it interferes with the title tag of the site. Any idea why this would be happening?

Without knowing which theme you're using, which plugins you're using, and which page you're referring to, it's hard to diagnose what may be causing this.

**Comment by themechills** [comment]
Hi Philip,

Hmmm, strange. Just got it working...

What I did was remove the second if statement, then declared the `the_subtitle()` tag where I wanted to apply it.

I'm thinking this is correct, though if you see an issue with this implementation I'm open to your feedback.

Thanks again,

Leo

**Comment by philiparthurmoore** [comment]
Sounds good Leo. That implementation is also totally fine. Thanks for letting me know. If you run into any other issues let me know and I'll be happy to look into it. Cheers.
