### ISSUE TITLE
Subtitles showing up strangely on recent post widget

### ISSUE THREAD

**Issue by JennaCos** [philiparthurmoore/Subtitles#51]
Hi! I really, really love this plugin, it looks amazing with my website theme! However I'm just having an issue with how it shows up in the recent post widget. I have the widget in a prominent place on the site, and I want to have only the post title and date underneath. But when I add a subtitle to the post it automatically comes up, and also comes up with the span tags for some reason. I'm attaching a screenshot.

I'm using the Recent Posts Extended widget plugin, and it has a space for custom CSS if that helps! 

![screen shot 2015-07-15 at 8 43 16 pm](https://cloud.githubusercontent.com/assets/13348447/8696716/23977176-2b32-11e5-8c31-2a3f288b6f06.png)

**Comment by philiparthurmoore** [comment]
@JennaCos So sorry for my late reply. This issue is likely due to the explanation outlined [here](https://github.com/philiparthurmoore/Subtitles#theres-weird-html-showing-up-on-my-site). Can you give me a link to the plugin that you're using? I can scan the code quickly and see if there's an issue with the way that it's displaying titles. Cheers.

**Comment by JennaCos** [comment]
Thanks! I'm using the Ink theme. 

http://themeforest.net/item/ink-a-wordpress-blogging-theme-to-tell-stories/7520750

Our site has a coming soon displayed because it's not launched yet, but in case you can still use it it's: http://www.the8percent.com

**Comment by philiparthurmoore** [comment]
@JennaCos Did you ever resolve this? I took a look at your site just now and it looks good. So sorry to have dropped the ball on this Issue. I can pick it up again if you're still having trouble.

**Comment by JennaCos** [comment]
Hi, I wasn’t able to resolve it, so I just switched to a different plugin, sorry. 

Jenna Cosgrove
Marketing Strategist
Strategic Anarchy
Ph: 1300 10 30 50

**Comment by JennaCos** [comment]
Hi, I wasn’t able to resolve it, so I just switched to a different recent posts plugin. It took a lot of searching, but I finally found one that had all the features I wanted, and also worked with the subtitles!

**Comment by philiparthurmoore** [comment]
Fantastic. I will mark this resolved! Thanks so much for the heads up.
