### ISSUE TITLE
single_post_title() not showing subtitle outside of the loop

### ISSUE THREAD

**Issue by deviodigital** [philiparthurmoore/Subtitles#54]
I noticed there was an [issue](https://github.com/philiparthurmoore/Subtitles/issues/2) in 2014 about this, but I've been testing this plugin out and have the `single_post_title();` code in my theme's header.php file, but it's not outputting the subtitle.

When viewing the page source, it also looks like it's not effecting the title at all. The title output is just the plain WordPress post title output.

I tested the `single_post_title();` output within the loop, and that works fine.

Not sure if any of that info that helps, but figured I'd let you know.

**Comment by philiparthurmoore** [comment]
Thanks for letting me know. Subtitles will only show if they are [inside the Loop](https://github.com/philiparthurmoore/Subtitles#subtitles-dont-show-up-on-my-site). If you'd like to display them outside the loop then you might want to look into using `the_subtitle` or `get_the_subtitle` ([here](https://github.com/philiparthurmoore/Subtitles#using-template-tags)). Let me know how that goes for you.

**Comment by deviodigital** [comment]
Well, shit, that worked perfectly. Thanks again for an awesome plugin!

**Comment by philiparthurmoore** [comment]
Fantastic! Thanks for letting me know. Please leave me a review if you have
a moment. Cheers.
