### ISSUE TITLE
Incorrect HTML generated on blog posts page?

### ISSUE THREAD

**Issue by edwardterry** [philiparthurmoore/Subtitles#55]
I just installed the plugin which is excellent. But ... it appears to have an invalid HTML output on my blog home page (latest posts). Something weird going on in the featured-holder DIV. You can see it on www.hologram.me.uk and the first post (Excession) shows the issue right under the picture. This also appears on the actual post itself.

**Comment by philiparthurmoore** [comment]
Hi there. Have you seen [this](https://github.com/philiparthurmoore/Subtitles#theres-weird-html-showing-up-on-my-site)? Cheers.

**Comment by edwardterry** [comment]
Thanks for the quick response. It looks like the theme conflict ... I disabled the plugin and noticed the use of the post title in the place where the weird HTML appeared after I enabled it. This means the theme needs to be updated - I have now made temporary updates which solve the theme bug and will report these to the theme developer. Much appreciated!

**Comment by philiparthurmoore** [comment]
Thanks so much for the heads up. I'll close this but feel free to open another Issue if you run into any other potential bugs. And please leave me a review on WordPress.org if you enjoy the plugin. Thank you!
