### ISSUE TITLE
Tags to display subtitle on another page (plugin subtitles)

### ISSUE THREAD

**Issue by goncalocruz77** [philiparthurmoore/Subtitles#60]
Hi, I created a comun page on my domain and it pull my posts through the type tags <? Php the_permalink (); ?> <? Php the_title (); ?> And <? Php the_excerpt (); ?>. Use with wp-load.

I wonder with which I can bring the subtitle tag?

You do information on the plugin page.

Thank you.

**Comment by philiparthurmoore** [comment]
Answered here: https://wordpress.org/support/topic/tags-to-display-subtitle-on-another-page?replies=2#post-7471432.

**Comment by goncalocruz77** [comment]
Resolvido. Obrigado.
